version: '2'
services:
  glpi:
    image: indication/glpi-ocsinventory:latest
    #build: ./glpi
    ports:
      - 82:80
    environment:
      - DB_HOST=glpidb
      - DB_DATABASE=glpi
      - DB_USERNAME=glpi
      - DB_PASSWORD=glpipass
      - TZ=UTC
    links:
      - glpidb:glpidb
  glpidb:
    # the container only supports 5.x
    image: mysql:5
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      # If you want to change password, 
      # see mysql.init/10_glpi.sql
    command: --sql_mode=""
    volumes:
       - ./mysql.init:/docker-entrypoint-initdb.d:ro

