version: '2'
services:
  ocsinventory:
    image: indication/ocsinventory-ng:2.5
    #build: ./ocsinventory
    ports:
      - 83:80
    environment:
      - OCS_DBNAME=ocsinventory
      - OCS_DBSERVER_READ=glpidb
      - OCS_DBSERVER_WRITE=glpidb
      - OCS_DBUSER=ocsinventory
      - OCS_DBPASS=ocsinventorypass
    links:
      - glpidb:glpidb
  glpidb:
    # the container only supports 5.x
    image: mysql:5
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      # If you want to change password, 
      # see mysql.init/11_ocsinventory.sql
    command: --sql_mode=""
    volumes:
       - ./mysql.init:/docker-entrypoint-initdb.d:ro

