version: '2'
services:
  glpi:
    build: ./glpi
    ports:
      - 81:80
    environment:
      - DB_HOST=glpidb
      - DB_DATABASE=glpi
      - DB_USERNAME=glpi
      - DB_PASSWORD=glpipass
    links:
      - glpidb:glpidb
  glpidb:
    # snipe-it only supports 5.x
    image: mysql:5
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=glpi
      - MYSQL_USER=glpi
      - MYSQL_PASSWORD=glpipass
    command: --sql_mode=""
#    volumes:
#      - /mysql/dumps/dir:/docker-entrypoint-initdb.d

