version: '2'
services:
  glpi:
    build: ./glpi
    ports:
      - 82:80
    environment:
      - DB_HOST=glpidb
      - DB_DATABASE=glpi
      - DB_USERNAME=glpi
      - DB_PASSWORD=glpipass
    links:
      - glpidb:glpidb
  ocsinventory:
    build: ./ocsinventory
    ports:
      - 83:80
    environment:
      - OCS_DBNAME=ocsinventory
      - OCS_DBSERVER_READ=glpidb
      - OCS_DBSERVER_WRITE=glpidb
      - OCS_DBUSER=ocsinventory
      - OCS_DBPASS=ocsinventorypass
    links:
      - glpidb:glpidb
  glpidb:
    # snipe-it only supports 5.x
    image: mysql:5
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      #- MYSQL_DATABASE=glpi
      #- MYSQL_USER=glpi
      #- MYSQL_PASSWORD=glpipass
    command: --sql_mode=""
    volumes:
       - ./mysql.init:/docker-entrypoint-initdb.d:ro

